### ISSUE TITLE
Error in CiviCRM 4.6.6

### ISSUE THREAD

**Issue by CaioBianchi** [adixon/ca.civicrm.beanstream#2]
```
Strict warning: Declaration of CRM_Core_Payment_Beanstream::singleton() should be compatible with & CRM_Core_Payment::singleton($mode, &$paymentProcessor, &$paymentForm = NULL, $force = false) in Civi\Payment\System::getByProcessor()
```

https://github.com/drastik/com.drastikbydesign.stripe/issues/12
Other similar modules seem to have easily fixed this warning. Perhaps it's some subtle change to the code structure?

**Comment by adixon** [comment]
Yes, I haven't been paying attention to this extension, but this change to stripe:
https://github.com/drastik/com.drastikbydesign.stripe/commit/021e9a6d89b11b553965838f4eae1c05b6a65e87
should help fix this one for 4.6.
