### ISSUE TITLE
Reccuring payments

### ISSUE THREAD

**Issue by Keldion** [adixon/ca.civicrm.beanstream#6]
Hi,

This is more of a question but this extension only supports one-time payments still right ?

Thanks,

**Comment by adixon** [comment]
Great question ... your answer is correct, but it turns out I've got a client who needs recurring payments with beanstream as well, so I'm about to try re-implementing this as an omnipay plugin. I'd be happy if you're able to do some testing in the next couple of weeks.

**Comment by Keldion** [comment]
Hmm, interesting...

I need to investigate others factors for a payment gateway since I'm not sure we will stay with Beanstream. But do keep me posted, I should make a choice about this soon.

Furthermore I'm not a programmer but if the plugin is easy to update on our website I may be able to do some testing !

Thanks,

**Comment by Keldion** [comment]
Well, I'm done shopping gateways and we will go with Stripe, so I will not be able to help test the Beanstream plugin unfortunately !

**Comment by adixon** [comment]
Okay. Can I ask what tipped your choice to using Stripe? Just curiosity on my part.

**Comment by Keldion** [comment]
There is a lot of factors but it just fit more our needs.
- The stripe plugin already support recurring payments
- The plugin seems to be updated regularly
- No monthly fees
- Stripe refund transactions fees for refunded transactions (which mean
  lots of money for us since we refund tickets for volunteering hours)
- The setup is very simple
- I have annoying restrictions on my beanstream account since we are a
  high risk merchant (we organize events)

**Comment by adixon** [comment]
Cool, thanks. I'll close this, but not before making a plug for my preferred payment processor for CiviCRM, i.e. iATS Payments, in case Stripe doesn't work out for you.

**Comment by Keldion** [comment]
I will have a look at iATS ;)  It wasn't in the gateways I've checked.

Thanks,
